package video

data class Video(
    val id: Int = 0,
    val owner_id: Int = 0,
    val title: String = "",
    val description: String = "",
    val duration: Int = 0,
    val image: Array<Image>? = arrayOf(),
    val first_frame: Array<FirstFrame>? = arrayOf(),
    val date: Long = System.currentTimeMillis(),
    val adding_date: Long = System.currentTimeMillis(),
    val views: Int = 0,
    val local_views: Int = 0,
    val comments: Int = 0,
    val player: String = "",
    val platform: String = "",
    val can_add: Boolean = false,
    val is_private: Boolean = false,
    val access_key: String = "",
    val processing: Boolean = false,
    val is_favorite: Boolean = false,
    val can_comment: Boolean = false,
    val can_edit: Boolean = false,
    val can_like: Boolean = false,
    val can_repost: Boolean = false,
    val can_subscribe: Boolean = false,
    val can_add_to_faves: Boolean = false,
    val can_attach_link: Boolean = false,
    val width: Int = 0,
    val height: Int = 0,
    val user_id: Int = 0,
    val converting: Boolean = false,
    val added: Boolean = false,
    val is_subscribed: Boolean = false,
    val repeat: Boolean = false,
    val type: String = "",
    val balance: Int = 0,
    val live_status: String = "",
    val live: Boolean = false,
    val upcoming: Boolean = false,
    val spectators: Int = 0,
    val likes: VideoLike? = VideoLike(),
    val reposts: VideoRepost? = VideoRepost()
)