package posts

data class Post(
    val id: Int = 0,
    val ownerId: Int = 0,
    val fromId: Int = 0,
    val createdBy: Int? = 0,
    val date: Long = System.currentTimeMillis(),
    val text: String = "",
    val replyOwnerId: Int = 0,
    val replyPostId: Int = 0,
    val isFriendsOnly: Boolean = false,
    val comments: Comment? = Comment(),
    val copyright: String = "",
    val likes: Like? = Like(),
    val reposts: Repost? = Repost(),
    val views: View? = View(),
    val postType: String = "",
    val postSource: PostSource? = PostSource(),
    val geo: Geo? = Geo(),
    val signerId: Int = 0,
    val copyHistory: Array<Repost>? = arrayOf(),
    val canPin: Boolean = false,
    val canDelete: Boolean = false,
    val canEdit: Boolean = false,
    val isPinned: Boolean = false,
    val markedAsAds: Boolean = false,
    val isFavorite: Boolean = false,
    val postponedId: Int = 0,
)